EpgList.py: Convert time to integer (python 3.10)
Sooner or later OE-core will update to Python 3.10.x.
No problem to apply patch now.

Fix for crash:

File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 212, in onCreate
    l.fillSingleEPG(service)
  File "/usr/lib/enigma2/python/Components/EpgList.py", line 345, in fillSingleEPG
    self.list = self.queryEPG(test)
  File "/usr/lib/enigma2/python/Components/EpgList.py", line 313, in queryEPG
    return self.epgcache.lookupEvent(list)
SystemError: <built-in function eEPGCache_lookupEvent> returned a result with an exception set